#pragma config(Sensor, port1,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port2,  leftEncoder,    sensorVexIQ_Distance)
#pragma config(Sensor, port3,  rightEncoder,   sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          leftFront,     tmotorNone, openLoop)
#pragma config(Motor,  motor2,          leftBack,      tmotorNone, openLoop)
#pragma config(Motor,  motor3,          rightFront,    tmotorNone, openLoop)
#pragma config(Motor,  motor4,          rightBack,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          intake,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          launcher,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightMid,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          leftMid,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          leftArm,       tmotorNone, openLoop)
#pragma config(Motor,  motor10,         rightArm,      tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnLeft(int speed){
	motor[rightFront]=speed;
	motor[rightBack]=speed;
}

void turnRight(int speed){
	motor[leftFront]=speed;
	motor[leftBack]=speed;
}
void moveForward(int speed){
	turnLeft(speed);
	turnRight(speed);
}
//Control intake
void intakecntrl(int speed){
	motor[intake]=speed;
}
//Lowers or raises arms to flip cap
void armCntrl(int speed){
	motor[rightArm]=speed;
	motor[leftArm]=speed;
}

task main()
{
	//Begins task of getting cap
	armCntrl(-100);
	wait1Msec(1000);
	armCntrl(0);
	moveForward(120);
	wait1Msec(2500);
	moveForward(0);
	/**
		Note: Code here is experimental to flip cap using stupid ideas
		armCntrl(127);	//Assuming tip of arm is at tip of cap
		wait1M(1000);
		armCntrl(0);
		moveForward(-120);
		wait1Msec(1000);
		moveForward(0);
	**/
	armCntrl(100);
	wait1Msec(1000);
	armCntrl(0);
	moveForward(50);
	wait1Msec(1000);
	moveForward(0);
	while(abs( SensorValue[gyro] ) < 900) {
        turnRight(120);
   }
	armCntrl(-100);				//puts cap on pole
	wait1Msec(1000);
	armCntrl(0);
	moveForward(-100);
	wait1Msec(1000);
	while(abs( SensorValue[gyro] ) < 900) {
        turnLeft(120);
   }

}
